# reusable config stanzas
only-release-tags: &only-release-tags
  filters:
    tags:
      only: /v[0-9]+\.[0-9]+\.[0-9]+.*/
    branches:
      ignore: /.*/

# start of config
version: 2.1

executors:
  nodejs:
    docker:
      - image: madsci/circleci-node:12.16
    working_directory: ~/repo
    shell: /bin/bash

commands:
  restore-node-cache:
    steps:
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package-lock.json" }}
            - v1-npm-

  save-node-cache:
    steps:
      - save_cache:
          paths:
            - '~/.npm'
            - node_modules
          key: v1-npm-{{ checksum "package-lock.json" }}

  configure-npm:
    steps:
      - run:
          name: Configuring NPM authentication
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            echo OK

  build-app:
    steps:
      - run:
          name: Building application
          command: npm run build
      - run:
          name: Checking build worked correctly
          command: |
            if [ ! -f ./dist/index.js ]; then
              echo "Something went wrong: no ./dist/index.js file was built!"
              exit 1
            else
              echo "Build appears to be successful: ./dist/index.js was created"
            fi

jobs:
  test:
    executor: nodejs
    steps:
      - checkout
      - restore-node-cache
      - configure-npm
      - run:
          name: Installing dependencies with NPM
          command: npm ci
      - save-node-cache
      - run:
          name: Linting source code
          command: npm run lint
      - run:
          name: Running project tests
          command: npm run test:ci
      - store_test_results:
          path: ./test/.results

  build:
    executor: nodejs
    steps:
      - checkout
      - restore-node-cache
      - build-app

  publish:
    executor: nodejs
    steps:
      - checkout
      - restore-node-cache
      - run:
          name: Configuring NPM authentication
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN_PUBLISHING}" >> ~/.npmrc
      - build-app
      - run:
          name: Copying extra files into dist directory
          command: cp package.json README* dist/
      - run:
          name: Publishing package to NPM registry
          command: npm publish dist

workflows:
  version: 2

  Test:
    jobs:
      - test
      - build:
          requires:
            - test

  Release:
    jobs:
      - test:
          <<: *only-release-tags
      - publish:
          <<: *only-release-tags
          requires:
            - test
